
# 数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exam_online_sys?serverTimezone=GMT%2B8&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: fuck3148481
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# 日志配置（开发用）
logging:
  level:
    com:
      longder: DEBUG
# 服务端口
server:
  port: 5188

system:
  default-password: 1234  # 默认密码
  mistake-step: 5  #增加难度的错误数
